export const SWITCH_MAIN_TAB = 'SWITCH_MAIN_TAB';

//todo action types
export const START_FETCH_ALL_TODOS = 'START_FETCH_ALL_TODOS';
export const FETCH_ALL_TODOS = 'FETCH_ALL_TODOS';


export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const TEST = 'TEST';

//home
export const FETCH_ALL_HOME_LIST = 'FETCH_ALL_HOME_LIST';
export const START_FETCH_ALL_HOME_LIST = 'START_FETCH_ALL_HOME_LIST';
export const RERESH_HOME_LIST = 'RERESH_HOME_LIST';
export const MORE_HOME_LIST = 'MORE_HOME_LIST';
export const START_FETCH_MORE_HOME_LIST = 'START_FETCH_MORE_HOME_LIST';

//discovery
export const FETCH_ALL_DISCOVERY_LIST = 'FETCH_ALL_DISCOVERY_LIST';
export const START_ALL_DISCOVERY_LIST = 'START_ALL_DISCOVERY_LIST';
export const REFRESH_ALL_DISCOVERY_LIST = 'REFRESH_ALL_DISCOVERY_LIST';

//publish
export const PUBLSIH = 'PUBLISH';
export const PUBLSIH_SELECT_IMAGES = 'PUBLSIH_SELECT_IMAGES';

//personal
export const PERSONAL = 'PERSONAL';